# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import asset_pb2 as asset__pb2
from . import location_pb2 as location__pb2


class AssetStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
        """Constructor.

        Args:
          channel: A grpc.Channel.
        """
        self.GetAsset = channel.unary_unary(
            '/lighting.asset.Asset/GetAsset',
            request_serializer=asset__pb2.Request.SerializeToString,
            response_deserializer=asset__pb2.Reply.FromString,
        )
        self.ListAssets = channel.unary_stream(
            '/lighting.asset.Asset/ListAssets',
            request_serializer=asset__pb2.ListRequest.SerializeToString,
            response_deserializer=asset__pb2.List.FromString,
        )
        self.SearchElements = channel.unary_stream(
            '/lighting.asset.Asset/SearchElements',
            request_serializer=location__pb2.FilterByLocationRequest.SerializeToString,
            response_deserializer=asset__pb2.Reply.FromString,
        )


class AssetServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def GetAsset(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAssets(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchElements(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AssetServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'GetAsset': grpc.unary_unary_rpc_method_handler(
            servicer.GetAsset,
            request_deserializer=asset__pb2.Request.FromString,
            response_serializer=asset__pb2.Reply.SerializeToString,
        ),
        'ListAssets': grpc.unary_stream_rpc_method_handler(
            servicer.ListAssets,
            request_deserializer=asset__pb2.ListRequest.FromString,
            response_serializer=asset__pb2.List.SerializeToString,
        ),
        'SearchElements': grpc.unary_stream_rpc_method_handler(
            servicer.SearchElements,
            request_deserializer=location__pb2.FilterByLocationRequest.FromString,
            response_serializer=asset__pb2.Reply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'lighting.asset.Asset', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
