# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: asset.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

from . import location_pb2 as location__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
    name='asset.proto',
    package='lighting.asset',
    syntax='proto3',
    serialized_options=None,
    serialized_pb=_b(
        '\n\x0b\x61sset.proto\x12\x0elighting.asset\x1a\x0elocation.proto\",\n\x0bListRequest\x12\r\n\x05limit\x18\x01 \x01(\x05\x12\x0e\n\x06offset\x18\x02 \x01(\x05\"\x15\n\x07Request\x12\n\n\x02id\x18\x01 \x01(\x05\"\x13\n\x05Reply\x12\n\n\x02id\x18\x01 \x01(\x05\"-\n\x04List\x12%\n\x06\x61ssets\x18\x01 \x03(\x0b\x32\x15.lighting.asset.Reply2\xdd\x01\n\x05\x41sset\x12:\n\x08GetAsset\x12\x17.lighting.asset.Request\x1a\x15.lighting.asset.Reply\x12\x41\n\nListAssets\x12\x1b.lighting.asset.ListRequest\x1a\x14.lighting.asset.List0\x01\x12U\n\x0eSearchElements\x12*.lighting.location.FilterByLocationRequest\x1a\x15.lighting.asset.Reply0\x01\x62\x06proto3')
    ,
    dependencies=[location__pb2.DESCRIPTOR, ])

_LISTREQUEST = _descriptor.Descriptor(
    name='ListRequest',
    full_name='lighting.asset.ListRequest',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='limit', full_name='lighting.asset.ListRequest.limit', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='offset', full_name='lighting.asset.ListRequest.offset', index=1,
            number=2, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=47,
    serialized_end=91,
)

_REQUEST = _descriptor.Descriptor(
    name='Request',
    full_name='lighting.asset.Request',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='id', full_name='lighting.asset.Request.id', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=93,
    serialized_end=114,
)

_REPLY = _descriptor.Descriptor(
    name='Reply',
    full_name='lighting.asset.Reply',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='id', full_name='lighting.asset.Reply.id', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=116,
    serialized_end=135,
)

_LIST = _descriptor.Descriptor(
    name='List',
    full_name='lighting.asset.List',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='assets', full_name='lighting.asset.List.assets', index=0,
            number=1, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=137,
    serialized_end=182,
)

_LIST.fields_by_name['assets'].message_type = _REPLY
DESCRIPTOR.message_types_by_name['ListRequest'] = _LISTREQUEST
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Reply'] = _REPLY
DESCRIPTOR.message_types_by_name['List'] = _LIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ListRequest = _reflection.GeneratedProtocolMessageType('ListRequest', (_message.Message,), {
    'DESCRIPTOR': _LISTREQUEST,
    '__module__': 'asset_pb2'
    # @@protoc_insertion_point(class_scope:lighting.asset.ListRequest)
})
_sym_db.RegisterMessage(ListRequest)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
    'DESCRIPTOR': _REQUEST,
    '__module__': 'asset_pb2'
    # @@protoc_insertion_point(class_scope:lighting.asset.Request)
})
_sym_db.RegisterMessage(Request)

Reply = _reflection.GeneratedProtocolMessageType('Reply', (_message.Message,), {
    'DESCRIPTOR': _REPLY,
    '__module__': 'asset_pb2'
    # @@protoc_insertion_point(class_scope:lighting.asset.Reply)
})
_sym_db.RegisterMessage(Reply)

List = _reflection.GeneratedProtocolMessageType('List', (_message.Message,), {
    'DESCRIPTOR': _LIST,
    '__module__': 'asset_pb2'
    # @@protoc_insertion_point(class_scope:lighting.asset.List)
})
_sym_db.RegisterMessage(List)

_ASSET = _descriptor.ServiceDescriptor(
    name='Asset',
    full_name='lighting.asset.Asset',
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    serialized_start=185,
    serialized_end=406,
    methods=[
        _descriptor.MethodDescriptor(
            name='GetAsset',
            full_name='lighting.asset.Asset.GetAsset',
            index=0,
            containing_service=None,
            input_type=_REQUEST,
            output_type=_REPLY,
            serialized_options=None,
        ),
        _descriptor.MethodDescriptor(
            name='ListAssets',
            full_name='lighting.asset.Asset.ListAssets',
            index=1,
            containing_service=None,
            input_type=_LISTREQUEST,
            output_type=_LIST,
            serialized_options=None,
        ),
        _descriptor.MethodDescriptor(
            name='SearchElements',
            full_name='lighting.asset.Asset.SearchElements',
            index=2,
            containing_service=None,
            input_type=location__pb2._FILTERBYLOCATIONREQUEST,
            output_type=_REPLY,
            serialized_options=None,
        ),
    ])
_sym_db.RegisterServiceDescriptor(_ASSET)

DESCRIPTOR.services_by_name['Asset'] = _ASSET

# @@protoc_insertion_point(module_scope)
