# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import basestation_pb2 as basestation__pb2
from . import location_pb2 as location__pb2


class BasestationStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
        """Constructor.

        Args:
          channel: A grpc.Channel.
        """
        self.GetBasestation = channel.unary_unary(
            '/lighting.basestation.Basestation/GetBasestation',
            request_serializer=basestation__pb2.Request.SerializeToString,
            response_deserializer=basestation__pb2.Reply.FromString,
        )
        self.ListBasestations = channel.unary_stream(
            '/lighting.basestation.Basestation/ListBasestations',
            request_serializer=basestation__pb2.List.SerializeToString,
            response_deserializer=basestation__pb2.List.FromString,
        )
        self.SearchBasestations = channel.unary_stream(
            '/lighting.basestation.Basestation/SearchBasestations',
            request_serializer=location__pb2.FilterByLocationRequest.SerializeToString,
            response_deserializer=basestation__pb2.Reply.FromString,
        )


class BasestationServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def GetBasestation(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBasestations(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchBasestations(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BasestationServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'GetBasestation': grpc.unary_unary_rpc_method_handler(
            servicer.GetBasestation,
            request_deserializer=basestation__pb2.Request.FromString,
            response_serializer=basestation__pb2.Reply.SerializeToString,
        ),
        'ListBasestations': grpc.unary_stream_rpc_method_handler(
            servicer.ListBasestations,
            request_deserializer=basestation__pb2.List.FromString,
            response_serializer=basestation__pb2.List.SerializeToString,
        ),
        'SearchBasestations': grpc.unary_stream_rpc_method_handler(
            servicer.SearchBasestations,
            request_deserializer=location__pb2.FilterByLocationRequest.FromString,
            response_serializer=basestation__pb2.Reply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'lighting.basestation.Basestation', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
