# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: basestation.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

from . import location_pb2 as location__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
    name='basestation.proto',
    package='lighting.basestation',
    syntax='proto3',
    serialized_options=None,
    serialized_pb=_b(
        '\n\x11\x62\x61sestation.proto\x12\x14lighting.basestation\x1a\x0elocation.proto\"<\n\x07Request\x12\x0c\n\x02id\x18\x01 \x01(\x05H\x00\x12\x0e\n\x04uuid\x18\x02 \x01(\x05H\x00\x42\x13\n\x11unique_identifier\"\x97\x01\n\x05Reply\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04uuid\x18\x02 \x01(\x03\x12\x0f\n\x07version\x18\x03 \x01(\x05\x12\x34\n\x06status\x18\x04 \x01(\x0e\x32$.lighting.basestation.ActivityStatus\x12-\n\x08location\x18\x0f \x01(\x0b\x32\x1b.lighting.location.Location\"9\n\x04List\x12\x31\n\x0c\x62\x61sestations\x18\x01 \x03(\x0b\x32\x1b.lighting.basestation.Reply*;\n\x0e\x41\x63tivityStatus\x12\x0f\n\x0bUNAVAILABLE\x10\x00\x12\n\n\x06\x41\x43TIVE\x10\x01\x12\x0c\n\x08INACTIVE\x10\x02\x32\x8a\x02\n\x0b\x42\x61sestation\x12L\n\x0eGetBasestation\x12\x1d.lighting.basestation.Request\x1a\x1b.lighting.basestation.Reply\x12L\n\x10ListBasestations\x12\x1a.lighting.basestation.List\x1a\x1a.lighting.basestation.List0\x01\x12_\n\x12SearchBasestations\x12*.lighting.location.FilterByLocationRequest\x1a\x1b.lighting.basestation.Reply0\x01\x62\x06proto3')
    ,
    dependencies=[location__pb2.DESCRIPTOR, ])

_ACTIVITYSTATUS = _descriptor.EnumDescriptor(
    name='ActivityStatus',
    full_name='lighting.basestation.ActivityStatus',
    filename=None,
    file=DESCRIPTOR,
    values=[
        _descriptor.EnumValueDescriptor(
            name='UNAVAILABLE', index=0, number=0,
            serialized_options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='ACTIVE', index=1, number=1,
            serialized_options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='INACTIVE', index=2, number=2,
            serialized_options=None,
            type=None),
    ],
    containing_type=None,
    serialized_options=None,
    serialized_start=334,
    serialized_end=393,
)
_sym_db.RegisterEnumDescriptor(_ACTIVITYSTATUS)

ActivityStatus = enum_type_wrapper.EnumTypeWrapper(_ACTIVITYSTATUS)
UNAVAILABLE = 0
ACTIVE = 1
INACTIVE = 2

_REQUEST = _descriptor.Descriptor(
    name='Request',
    full_name='lighting.basestation.Request',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='id', full_name='lighting.basestation.Request.id', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='uuid', full_name='lighting.basestation.Request.uuid', index=1,
            number=2, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
        _descriptor.OneofDescriptor(
            name='unique_identifier', full_name='lighting.basestation.Request.unique_identifier',
            index=0, containing_type=None, fields=[]),
    ],
    serialized_start=59,
    serialized_end=119,
)

_REPLY = _descriptor.Descriptor(
    name='Reply',
    full_name='lighting.basestation.Reply',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='id', full_name='lighting.basestation.Reply.id', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='uuid', full_name='lighting.basestation.Reply.uuid', index=1,
            number=2, type=3, cpp_type=2, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='version', full_name='lighting.basestation.Reply.version', index=2,
            number=3, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='status', full_name='lighting.basestation.Reply.status', index=3,
            number=4, type=14, cpp_type=8, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='location', full_name='lighting.basestation.Reply.location', index=4,
            number=15, type=11, cpp_type=10, label=1,
            has_default_value=False, default_value=None,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=122,
    serialized_end=273,
)

_LIST = _descriptor.Descriptor(
    name='List',
    full_name='lighting.basestation.List',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='basestations', full_name='lighting.basestation.List.basestations', index=0,
            number=1, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=275,
    serialized_end=332,
)

_REQUEST.oneofs_by_name['unique_identifier'].fields.append(
    _REQUEST.fields_by_name['id'])
_REQUEST.fields_by_name['id'].containing_oneof = _REQUEST.oneofs_by_name['unique_identifier']
_REQUEST.oneofs_by_name['unique_identifier'].fields.append(
    _REQUEST.fields_by_name['uuid'])
_REQUEST.fields_by_name['uuid'].containing_oneof = _REQUEST.oneofs_by_name['unique_identifier']
_REPLY.fields_by_name['status'].enum_type = _ACTIVITYSTATUS
_REPLY.fields_by_name['location'].message_type = location__pb2._LOCATION
_LIST.fields_by_name['basestations'].message_type = _REPLY
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Reply'] = _REPLY
DESCRIPTOR.message_types_by_name['List'] = _LIST
DESCRIPTOR.enum_types_by_name['ActivityStatus'] = _ACTIVITYSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
    'DESCRIPTOR': _REQUEST,
    '__module__': 'basestation_pb2'
    # @@protoc_insertion_point(class_scope:lighting.basestation.Request)
})
_sym_db.RegisterMessage(Request)

Reply = _reflection.GeneratedProtocolMessageType('Reply', (_message.Message,), {
    'DESCRIPTOR': _REPLY,
    '__module__': 'basestation_pb2'
    # @@protoc_insertion_point(class_scope:lighting.basestation.Reply)
})
_sym_db.RegisterMessage(Reply)

List = _reflection.GeneratedProtocolMessageType('List', (_message.Message,), {
    'DESCRIPTOR': _LIST,
    '__module__': 'basestation_pb2'
    # @@protoc_insertion_point(class_scope:lighting.basestation.List)
})
_sym_db.RegisterMessage(List)

_BASESTATION = _descriptor.ServiceDescriptor(
    name='Basestation',
    full_name='lighting.basestation.Basestation',
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    serialized_start=396,
    serialized_end=662,
    methods=[
        _descriptor.MethodDescriptor(
            name='GetBasestation',
            full_name='lighting.basestation.Basestation.GetBasestation',
            index=0,
            containing_service=None,
            input_type=_REQUEST,
            output_type=_REPLY,
            serialized_options=None,
        ),
        _descriptor.MethodDescriptor(
            name='ListBasestations',
            full_name='lighting.basestation.Basestation.ListBasestations',
            index=1,
            containing_service=None,
            input_type=_LIST,
            output_type=_LIST,
            serialized_options=None,
        ),
        _descriptor.MethodDescriptor(
            name='SearchBasestations',
            full_name='lighting.basestation.Basestation.SearchBasestations',
            index=2,
            containing_service=None,
            input_type=location__pb2._FILTERBYLOCATIONREQUEST,
            output_type=_REPLY,
            serialized_options=None,
        ),
    ])
_sym_db.RegisterServiceDescriptor(_BASESTATION)

DESCRIPTOR.services_by_name['Basestation'] = _BASESTATION

# @@protoc_insertion_point(module_scope)
