# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import element_pb2 as element__pb2
from . import location_pb2 as location__pb2


class ElementStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
        """Constructor.

        Args:
          channel: A grpc.Channel.
        """
    self.GetElement = channel.unary_unary(
        '/lighting.element.Element/GetElement',
        request_serializer=element__pb2.Request.SerializeToString,
        response_deserializer=element__pb2.Reply.FromString,
        )
    self.ListElements = channel.unary_stream(
        '/lighting.element.Element/ListElements',
        request_serializer=element__pb2.ListRequest.SerializeToString,
        response_deserializer=element__pb2.List.FromString,
    )
    self.SearchElements = channel.unary_stream(
        '/lighting.element.Element/SearchElements',
        request_serializer=location__pb2.FilterByLocationRequest.SerializeToString,
        response_deserializer=element__pb2.Reply.FromString,
    )


class ElementServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetElement(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListElements(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SearchElements(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ElementServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetElement': grpc.unary_unary_rpc_method_handler(
          servicer.GetElement,
          request_deserializer=element__pb2.Request.FromString,
          response_serializer=element__pb2.Reply.SerializeToString,
      ),
      'ListElements': grpc.unary_stream_rpc_method_handler(
          servicer.ListElements,
          request_deserializer=element__pb2.ListRequest.FromString,
          response_serializer=element__pb2.List.SerializeToString,
      ),
      'SearchElements': grpc.unary_stream_rpc_method_handler(
          servicer.SearchElements,
          request_deserializer=location__pb2.FilterByLocationRequest.FromString,
          response_serializer=element__pb2.Reply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'lighting.element.Element', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
