# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: element.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

from . import location_pb2 as location__pb2
from . import asset_pb2 as asset__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
    name='element.proto',
    package='lighting.element',
    syntax='proto3',
    serialized_options=None,
    serialized_pb=_b(
        '\n\relement.proto\x12\x10lighting.element\x1a\x0elocation.proto\x1a\x0b\x61sset.proto\",\n\x0bListRequest\x12\r\n\x05limit\x18\x01 \x01(\x05\x12\x0e\n\x06offset\x18\x02 \x01(\x05\"\x15\n\x07Request\x12\n\n\x02id\x18\x01 \x01(\x05\"\xaf\x01\n\x05Reply\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x30\n\x06status\x18\x02 \x01(\x0e\x32 .lighting.element.ActivityStatus\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12$\n\x05\x61sset\x18\x04 \x01(\x0b\x32\x15.lighting.asset.Reply\x12-\n\x08location\x18\x0f \x01(\x0b\x32\x1b.lighting.location.Location\"1\n\x04List\x12)\n\x08\x65lements\x18\x01 \x03(\x0b\x32\x17.lighting.element.Reply*H\n\x0e\x41\x63tivityStatus\x12\x0f\n\x0bUNAVAILABLE\x10\x00\x12\n\n\x06\x41\x43TIVE\x10\x01\x12\x0c\n\x08INACTIVE\x10\x02\x12\x0b\n\x07\x44\x45LETED\x10\x0f\x32\xed\x01\n\x07\x45lement\x12@\n\nGetElement\x12\x19.lighting.element.Request\x1a\x17.lighting.element.Reply\x12G\n\x0cListElements\x12\x1d.lighting.element.ListRequest\x1a\x16.lighting.element.List0\x01\x12W\n\x0eSearchElements\x12*.lighting.location.FilterByLocationRequest\x1a\x17.lighting.element.Reply0\x01\x62\x06proto3')
    ,
    dependencies=[location__pb2.DESCRIPTOR, asset__pb2.DESCRIPTOR, ])

_ACTIVITYSTATUS = _descriptor.EnumDescriptor(
  name='ActivityStatus',
  full_name='lighting.element.ActivityStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNAVAILABLE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTIVE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
        name='INACTIVE', index=2, number=2,
        serialized_options=None,
        type=None),
      _descriptor.EnumValueDescriptor(
          name='DELETED', index=3, number=15,
          serialized_options=None,
          type=None),
  ],
    containing_type=None,
    serialized_options=None,
    serialized_start=362,
    serialized_end=434,
)
_sym_db.RegisterEnumDescriptor(_ACTIVITYSTATUS)

ActivityStatus = enum_type_wrapper.EnumTypeWrapper(_ACTIVITYSTATUS)
UNAVAILABLE = 0
ACTIVE = 1
INACTIVE = 2
DELETED = 15

_LISTREQUEST = _descriptor.Descriptor(
    name='ListRequest',
    full_name='lighting.element.ListRequest',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='limit', full_name='lighting.element.ListRequest.limit', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='offset', full_name='lighting.element.ListRequest.offset', index=1,
            number=2, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
  extensions=[
  ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=64,
    serialized_end=108,
)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='lighting.element.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='lighting.element.Request.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=110,
    serialized_end=131,
)


_REPLY = _descriptor.Descriptor(
  name='Reply',
  full_name='lighting.element.Reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='lighting.element.Reply.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
        is_extension=False, extension_scope=None,
        serialized_options=None, file=DESCRIPTOR),
      _descriptor.FieldDescriptor(
          name='status', full_name='lighting.element.Reply.status', index=1,
          number=2, type=14, cpp_type=8, label=1,
          has_default_value=False, default_value=0,
          message_type=None, enum_type=None, containing_type=None,
          is_extension=False, extension_scope=None,
          serialized_options=None, file=DESCRIPTOR),
      _descriptor.FieldDescriptor(
          name='description', full_name='lighting.element.Reply.description', index=2,
          number=3, type=9, cpp_type=9, label=1,
          has_default_value=False, default_value=_b("").decode('utf-8'),
          message_type=None, enum_type=None, containing_type=None,
          is_extension=False, extension_scope=None,
          serialized_options=None, file=DESCRIPTOR),
      _descriptor.FieldDescriptor(
          name='asset', full_name='lighting.element.Reply.asset', index=3,
          number=4, type=11, cpp_type=10, label=1,
          has_default_value=False, default_value=None,
          message_type=None, enum_type=None, containing_type=None,
          is_extension=False, extension_scope=None,
          serialized_options=None, file=DESCRIPTOR),
      _descriptor.FieldDescriptor(
          name='location', full_name='lighting.element.Reply.location', index=4,
          number=15, type=11, cpp_type=10, label=1,
          has_default_value=False, default_value=None,
          message_type=None, enum_type=None, containing_type=None,
          is_extension=False, extension_scope=None,
          serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=134,
    serialized_end=309,
)


_LIST = _descriptor.Descriptor(
  name='List',
  full_name='lighting.element.List',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='elements', full_name='lighting.element.List.elements', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=311,
    serialized_end=360,
)

_REPLY.fields_by_name['status'].enum_type = _ACTIVITYSTATUS
_REPLY.fields_by_name['asset'].message_type = asset__pb2._REPLY
_REPLY.fields_by_name['location'].message_type = location__pb2._LOCATION
_LIST.fields_by_name['elements'].message_type = _REPLY
DESCRIPTOR.message_types_by_name['ListRequest'] = _LISTREQUEST
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Reply'] = _REPLY
DESCRIPTOR.message_types_by_name['List'] = _LIST
DESCRIPTOR.enum_types_by_name['ActivityStatus'] = _ACTIVITYSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ListRequest = _reflection.GeneratedProtocolMessageType('ListRequest', (_message.Message,), {
    'DESCRIPTOR': _LISTREQUEST,
    '__module__': 'element_pb2'
    # @@protoc_insertion_point(class_scope:lighting.element.ListRequest)
})
_sym_db.RegisterMessage(ListRequest)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'element_pb2'
  # @@protoc_insertion_point(class_scope:lighting.element.Request)
  })
_sym_db.RegisterMessage(Request)

Reply = _reflection.GeneratedProtocolMessageType('Reply', (_message.Message,), {
  'DESCRIPTOR' : _REPLY,
  '__module__' : 'element_pb2'
  # @@protoc_insertion_point(class_scope:lighting.element.Reply)
  })
_sym_db.RegisterMessage(Reply)

List = _reflection.GeneratedProtocolMessageType('List', (_message.Message,), {
  'DESCRIPTOR' : _LIST,
  '__module__' : 'element_pb2'
  # @@protoc_insertion_point(class_scope:lighting.element.List)
  })
_sym_db.RegisterMessage(List)



_ELEMENT = _descriptor.ServiceDescriptor(
    name='Element',
    full_name='lighting.element.Element',
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    serialized_start=437,
    serialized_end=674,
    methods=[
        _descriptor.MethodDescriptor(
            name='GetElement',
            full_name='lighting.element.Element.GetElement',
            index=0,
            containing_service=None,
            input_type=_REQUEST,
            output_type=_REPLY,
            serialized_options=None,
        ),
  _descriptor.MethodDescriptor(
      name='ListElements',
      full_name='lighting.element.Element.ListElements',
      index=1,
      containing_service=None,
      input_type=_LISTREQUEST,
      output_type=_LIST,
      serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
      name='SearchElements',
      full_name='lighting.element.Element.SearchElements',
      index=2,
      containing_service=None,
      input_type=location__pb2._FILTERBYLOCATIONREQUEST,
      output_type=_REPLY,
      serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ELEMENT)

DESCRIPTOR.services_by_name['Element'] = _ELEMENT

# @@protoc_insertion_point(module_scope)
