# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: telecell.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

from . import location_pb2 as location__pb2
from . import ts_pb2 as ts__pb2
from . import element_pb2 as element__pb2
from . import basestation_pb2 as basestation__pb2
from . import asset_pb2 as asset__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
  name='telecell.proto',
  package='lighting.telecell',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b(
    '\n\x0etelecell.proto\x12\x11lighting.telecell\x1a\x0elocation.proto\x1a\x08ts.proto\x1a\relement.proto\x1a\x11\x62\x61sestation.proto\x1a\x0b\x61sset.proto\",\n\x0bListRequest\x12\r\n\x05limit\x18\x01 \x01(\x05\x12\x0e\n\x06offset\x18\x02 \x01(\x05\"3\n\x04List\x12+\n\ttelecells\x18\x01 \x03(\x0b\x32\x18.lighting.telecell.Reply\"6\n\x07Request\x12\x0c\n\x02id\x18\x01 \x01(\x05H\x00\x12\x0e\n\x04uuid\x18\x02 \x01(\x05H\x00\x42\r\n\x0btelecell_id\"\xc1\x02\n\x05Reply\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04uuid\x18\x02 \x01(\x03\x12\r\n\x05relay\x18\x03 \x01(\x08\x12\x30\n\x0b\x62\x61sestation\x18\x04 \x01(\x0b\x32\x1b.lighting.basestation.Reply\x12\x31\n\x06status\x18\x05 \x01(\x0e\x32!.lighting.telecell.ActivityStatus\x12*\n\nupdated_at\x18\x06 \x01(\x0b\x32\x16.lighting.ts.Timestamp\x12)\n\x08\x65lements\x18\x07 \x03(\x0b\x32\x17.lighting.element.Reply\x12$\n\x05\x61sset\x18\x08 \x01(\x0b\x32\x15.lighting.asset.Reply\x12-\n\x08location\x18\x0f \x01(\x0b\x32\x1b.lighting.location.Location*;\n\x0e\x41\x63tivityStatus\x12\x0f\n\x0bUNAVAILABLE\x10\x00\x12\n\n\x06\x41\x43TIVE\x10\x01\x12\x0c\n\x08INACTIVE\x10\x02\x32\xf5\x01\n\x08Telecell\x12\x43\n\x0bGetTelecell\x12\x1a.lighting.telecell.Request\x1a\x18.lighting.telecell.Reply\x12J\n\rListTelecells\x12\x1e.lighting.telecell.ListRequest\x1a\x17.lighting.telecell.List0\x01\x12X\n\x0eSearchElements\x12*.lighting.location.FilterByLocationRequest\x1a\x18.lighting.telecell.Reply0\x01\x62\x06proto3')
  ,
  dependencies=[location__pb2.DESCRIPTOR, ts__pb2.DESCRIPTOR, element__pb2.DESCRIPTOR, basestation__pb2.DESCRIPTOR,
                asset__pb2.DESCRIPTOR, ])

_ACTIVITYSTATUS = _descriptor.EnumDescriptor(
  name='ActivityStatus',
  full_name='lighting.telecell.ActivityStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNAVAILABLE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTIVE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INACTIVE', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=589,
  serialized_end=648,
)
_sym_db.RegisterEnumDescriptor(_ACTIVITYSTATUS)

ActivityStatus = enum_type_wrapper.EnumTypeWrapper(_ACTIVITYSTATUS)
UNAVAILABLE = 0
ACTIVE = 1
INACTIVE = 2

_LISTREQUEST = _descriptor.Descriptor(
  name='ListRequest',
  full_name='lighting.telecell.ListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='limit', full_name='lighting.telecell.ListRequest.limit', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='offset', full_name='lighting.telecell.ListRequest.offset', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=154,
)

_LIST = _descriptor.Descriptor(
  name='List',
  full_name='lighting.telecell.List',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='telecells', full_name='lighting.telecell.List.telecells', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=207,
)

_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='lighting.telecell.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='lighting.telecell.Request.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='lighting.telecell.Request.uuid', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='telecell_id', full_name='lighting.telecell.Request.telecell_id',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=209,
  serialized_end=263,
)

_REPLY = _descriptor.Descriptor(
  name='Reply',
  full_name='lighting.telecell.Reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='lighting.telecell.Reply.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='lighting.telecell.Reply.uuid', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='relay', full_name='lighting.telecell.Reply.relay', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='basestation', full_name='lighting.telecell.Reply.basestation', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='lighting.telecell.Reply.status', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='updated_at', full_name='lighting.telecell.Reply.updated_at', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='elements', full_name='lighting.telecell.Reply.elements', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='asset', full_name='lighting.telecell.Reply.asset', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='location', full_name='lighting.telecell.Reply.location', index=8,
      number=15, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=266,
  serialized_end=587,
)

_LIST.fields_by_name['telecells'].message_type = _REPLY
_REQUEST.oneofs_by_name['telecell_id'].fields.append(
  _REQUEST.fields_by_name['id'])
_REQUEST.fields_by_name['id'].containing_oneof = _REQUEST.oneofs_by_name['telecell_id']
_REQUEST.oneofs_by_name['telecell_id'].fields.append(
  _REQUEST.fields_by_name['uuid'])
_REQUEST.fields_by_name['uuid'].containing_oneof = _REQUEST.oneofs_by_name['telecell_id']
_REPLY.fields_by_name['basestation'].message_type = basestation__pb2._REPLY
_REPLY.fields_by_name['status'].enum_type = _ACTIVITYSTATUS
_REPLY.fields_by_name['updated_at'].message_type = ts__pb2._TIMESTAMP
_REPLY.fields_by_name['elements'].message_type = element__pb2._REPLY
_REPLY.fields_by_name['asset'].message_type = asset__pb2._REPLY
_REPLY.fields_by_name['location'].message_type = location__pb2._LOCATION
DESCRIPTOR.message_types_by_name['ListRequest'] = _LISTREQUEST
DESCRIPTOR.message_types_by_name['List'] = _LIST
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Reply'] = _REPLY
DESCRIPTOR.enum_types_by_name['ActivityStatus'] = _ACTIVITYSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ListRequest = _reflection.GeneratedProtocolMessageType('ListRequest', (_message.Message,), {
  'DESCRIPTOR': _LISTREQUEST,
  '__module__': 'telecell_pb2'
  # @@protoc_insertion_point(class_scope:lighting.telecell.ListRequest)
})
_sym_db.RegisterMessage(ListRequest)

List = _reflection.GeneratedProtocolMessageType('List', (_message.Message,), {
  'DESCRIPTOR': _LIST,
  '__module__': 'telecell_pb2'
  # @@protoc_insertion_point(class_scope:lighting.telecell.List)
})
_sym_db.RegisterMessage(List)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR': _REQUEST,
  '__module__': 'telecell_pb2'
  # @@protoc_insertion_point(class_scope:lighting.telecell.Request)
})
_sym_db.RegisterMessage(Request)

Reply = _reflection.GeneratedProtocolMessageType('Reply', (_message.Message,), {
  'DESCRIPTOR': _REPLY,
  '__module__': 'telecell_pb2'
  # @@protoc_insertion_point(class_scope:lighting.telecell.Reply)
})
_sym_db.RegisterMessage(Reply)

_TELECELL = _descriptor.ServiceDescriptor(
  name='Telecell',
  full_name='lighting.telecell.Telecell',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=651,
  serialized_end=896,
  methods=[
    _descriptor.MethodDescriptor(
      name='GetTelecell',
      full_name='lighting.telecell.Telecell.GetTelecell',
      index=0,
      containing_service=None,
      input_type=_REQUEST,
      output_type=_REPLY,
      serialized_options=None,
    ),
    _descriptor.MethodDescriptor(
      name='ListTelecells',
      full_name='lighting.telecell.Telecell.ListTelecells',
      index=1,
      containing_service=None,
      input_type=_LISTREQUEST,
      output_type=_LIST,
      serialized_options=None,
    ),
    _descriptor.MethodDescriptor(
      name='SearchElements',
      full_name='lighting.telecell.Telecell.SearchElements',
      index=2,
      containing_service=None,
      input_type=location__pb2._FILTERBYLOCATIONREQUEST,
      output_type=_REPLY,
      serialized_options=None,
    ),
  ])
_sym_db.RegisterServiceDescriptor(_TELECELL)

DESCRIPTOR.services_by_name['Telecell'] = _TELECELL

# @@protoc_insertion_point(module_scope)
