# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import location_pb2 as location__pb2
from . import telecell_pb2 as telecell__pb2


class TelecellStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
        """Constructor.

        Args:
          channel: A grpc.Channel.
        """
        self.GetTelecell = channel.unary_unary(
            '/lighting.telecell.Telecell/GetTelecell',
            request_serializer=telecell__pb2.Request.SerializeToString,
            response_deserializer=telecell__pb2.Reply.FromString,
        )
        self.ListTelecells = channel.unary_stream(
            '/lighting.telecell.Telecell/ListTelecells',
            request_serializer=telecell__pb2.ListRequest.SerializeToString,
            response_deserializer=telecell__pb2.List.FromString,
        )
        self.SearchElements = channel.unary_stream(
            '/lighting.telecell.Telecell/SearchElements',
            request_serializer=location__pb2.FilterByLocationRequest.SerializeToString,
            response_deserializer=telecell__pb2.Reply.FromString,
        )


class TelecellServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def GetTelecell(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTelecells(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchElements(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TelecellServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'GetTelecell': grpc.unary_unary_rpc_method_handler(
            servicer.GetTelecell,
            request_deserializer=telecell__pb2.Request.FromString,
            response_serializer=telecell__pb2.Reply.SerializeToString,
        ),
        'ListTelecells': grpc.unary_stream_rpc_method_handler(
            servicer.ListTelecells,
            request_deserializer=telecell__pb2.ListRequest.FromString,
            response_serializer=telecell__pb2.List.SerializeToString,
        ),
        'SearchElements': grpc.unary_stream_rpc_method_handler(
            servicer.SearchElements,
            request_deserializer=location__pb2.FilterByLocationRequest.FromString,
            response_serializer=telecell__pb2.Reply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'lighting.telecell.Telecell', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
