# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import user_pb2 as user__pb2


class UserStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
        """Constructor.

        Args:
          channel: A grpc.Channel.
        """
        self.GetUser = channel.unary_unary(
            '/user.User/GetUser',
            request_serializer=user__pb2.Request.SerializeToString,
            response_deserializer=user__pb2.Reply.FromString,
        )


class UserServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def GetUser(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'GetUser': grpc.unary_unary_rpc_method_handler(
            servicer.GetUser,
            request_deserializer=user__pb2.Request.FromString,
            response_serializer=user__pb2.Reply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'user.User', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
