# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

from . import ts_pb2 as ts__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
    name='user.proto',
    package='user',
    syntax='proto3',
    serialized_options=None,
    serialized_pb=_b(
        '\n\nuser.proto\x12\x04user\x1a\x08ts.proto\"6\n\x07Request\x12\x0c\n\x02id\x18\x01 \x01(\x05H\x00\x12\x12\n\x08username\x18\x02 \x01(\tH\x00\x42\t\n\x07user_id\"}\n\x05Reply\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x13\n\x0bhashed_pass\x18\x03 \x01(\t\x12\x18\n\x04role\x18\x04 \x01(\x0e\x32\n.user.Role\x12\'\n\x07\x63reated\x18\x05 \x01(\x0b\x32\x16.lighting.ts.Timestamp*1\n\x04Role\x12\t\n\x05\x41\x44MIN\x10\x00\x12\x07\n\x03\x44\x45V\x10\x01\x12\x0b\n\x07MANAGER\x10\x02\x12\x08\n\x04USER\x10\x03\x32-\n\x04User\x12%\n\x07GetUser\x12\r.user.Request\x1a\x0b.user.Replyb\x06proto3')
    ,
    dependencies=[ts__pb2.DESCRIPTOR, ])

_ROLE = _descriptor.EnumDescriptor(
    name='Role',
    full_name='user.Role',
    filename=None,
    file=DESCRIPTOR,
    values=[
        _descriptor.EnumValueDescriptor(
            name='ADMIN', index=0, number=0,
            serialized_options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='DEV', index=1, number=1,
            serialized_options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='MANAGER', index=2, number=2,
            serialized_options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='USER', index=3, number=3,
            serialized_options=None,
            type=None),
    ],
    containing_type=None,
    serialized_options=None,
    serialized_start=213,
    serialized_end=262,
)
_sym_db.RegisterEnumDescriptor(_ROLE)

Role = enum_type_wrapper.EnumTypeWrapper(_ROLE)
ADMIN = 0
DEV = 1
MANAGER = 2
USER = 3

_REQUEST = _descriptor.Descriptor(
    name='Request',
    full_name='user.Request',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='id', full_name='user.Request.id', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='username', full_name='user.Request.username', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
        _descriptor.OneofDescriptor(
            name='user_id', full_name='user.Request.user_id',
            index=0, containing_type=None, fields=[]),
    ],
    serialized_start=30,
    serialized_end=84,
)

_REPLY = _descriptor.Descriptor(
    name='Reply',
    full_name='user.Reply',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='id', full_name='user.Reply.id', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='username', full_name='user.Reply.username', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='hashed_pass', full_name='user.Reply.hashed_pass', index=2,
            number=3, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='role', full_name='user.Reply.role', index=3,
            number=4, type=14, cpp_type=8, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='created', full_name='user.Reply.created', index=4,
            number=5, type=11, cpp_type=10, label=1,
            has_default_value=False, default_value=None,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=86,
    serialized_end=211,
)

_REQUEST.oneofs_by_name['user_id'].fields.append(
    _REQUEST.fields_by_name['id'])
_REQUEST.fields_by_name['id'].containing_oneof = _REQUEST.oneofs_by_name['user_id']
_REQUEST.oneofs_by_name['user_id'].fields.append(
    _REQUEST.fields_by_name['username'])
_REQUEST.fields_by_name['username'].containing_oneof = _REQUEST.oneofs_by_name['user_id']
_REPLY.fields_by_name['role'].enum_type = _ROLE
_REPLY.fields_by_name['created'].message_type = ts__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Reply'] = _REPLY
DESCRIPTOR.enum_types_by_name['Role'] = _ROLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
    'DESCRIPTOR': _REQUEST,
    '__module__': 'user_pb2'
    # @@protoc_insertion_point(class_scope:user.Request)
})
_sym_db.RegisterMessage(Request)

Reply = _reflection.GeneratedProtocolMessageType('Reply', (_message.Message,), {
    'DESCRIPTOR': _REPLY,
    '__module__': 'user_pb2'
    # @@protoc_insertion_point(class_scope:user.Reply)
})
_sym_db.RegisterMessage(Reply)

_USER = _descriptor.ServiceDescriptor(
    name='User',
    full_name='user.User',
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    serialized_start=264,
    serialized_end=309,
    methods=[
        _descriptor.MethodDescriptor(
            name='GetUser',
            full_name='user.User.GetUser',
            index=0,
            containing_service=None,
            input_type=_REQUEST,
            output_type=_REPLY,
            serialized_options=None,
        ),
    ])
_sym_db.RegisterServiceDescriptor(_USER)

DESCRIPTOR.services_by_name['User'] = _USER

# @@protoc_insertion_point(module_scope)
